### ISSUE TITLE
Route QRCode

### ISSUE THREAD

**Issue by dieonar** [sportfun/EIP-Server#10]
Une route qui permet d'envoyer le QR Code scanner depuis l'application.

Détails a voir avec l'equipe software (Victor, Clément, Elsa)

coté app mobile -> sert uniquement a scanner le QR Code et l'envoyer au serveur 

Envoyé avec un token pour savoir qui a scanner le code

**Comment by dieonar** [comment]
- Génération du QR Code par le launcher et envoi du code QR au serveur.
- Enregistrement du code QR coté serveur

- Scan du QR Code par l'application mobile et envoi du QR Code au serveur
- Si le code scanner par l'application mobile correspond a un QR déjà enregistrer, le taggé comme a renvoyer.

- Le launcher essaie de get périodiquement sur une route spécifique si quelqu'un a scanner le QR Code généré.

**Comment by BoraxKid** [comment]
Est-ce qu'un code comme convient ?

`08568682-aa76-4d49-9fc6-a81436c37f1c`

C'est ce que sort System.Guid.NewGuid() en C# (qui est sensé être toujours unique)

Est-ce que j'envoie aussi le `sportsfun:` ?

**Comment by BoraxKid** [comment]
La route pour créer le QR Code doit garder en memoire la valeur envoyée. Elle renvoie un message d'erreur si le code existe déjà, succès si c'est bon.

Depuis l'application mobile, l'utilisateur peut scanner le QR code affiché sur le menu du jeu. Quand il le scan il demande au serveur si c'est un code valide.
Si non, message d'erreur.
Si oui, succès et le code est associé à l'utilisateur qui l'a scanné.

Pendant ce temps, le launcher ping toutes les X secondes le serveur pour savoir si le code à été scanné. Quand il est scanné, le serveur répond un succès avec l'id(?) de l'user (là c'est un peu flou pour moi parce que c'est pas moi qui gère les connexions users etc donc je sais pas si il faut juste un id ou quoi).
