### ISSUE TITLE
Websocket Chat

### ISSUE THREAD

**Issue by dieonar** [sportfun/EIP-Server#12]
- Récupérer les conversations d'un utilisateur
- Récupérer les messages d'une conversation (+ pagination)
- Envoyer un message a un utilisateur
- Recevoir les message d'un autre utilisateur

**Comment by Xobtah** [comment]
Il ne reste plus que la pagination

**Comment by dieonar** [comment]
Ajouter le nom + prénom de la personne qui envoie le message dans le channel "message"
