### ISSUE TITLE
http://api.sportsfun.shr.ovh:8080/api/message/:id

### ISSUE THREAD

**Issue by dieonar** [sportfun/EIP-Server#2]
La route pour récupérer les messages d'une conversation fonctionne pas, dans le sens où il y en a un des deux qui peut pas récupérer les messages (le receiver)

**Comment by Xobtah** [comment]
À tester, ça devrait être réglé

**Comment by dieonar** [comment]
c'est toujours pareil

**Comment by Xobtah** [comment]
A tester
