### ISSUE TITLE
GET: http://api.sportsfun.shr.ovh:8080/api/message

### ISSUE THREAD

**Issue by dieonar** [sportfun/EIP-Server#4]
Il faudrait rajouter les infos pour les deux users (celui qui envoi et celui qui reçoit) nom + prénom + photo de profil

**Comment by Xobtah** [comment]
C'est envoyé, fais des tests, si ça fonctionne dis-le moi pour que je merge dans master, si ça fonctionne pas on continue l'issue

**Comment by dieonar** [comment]
<img width="335" alt="screenshot 2018-09-04 at 08 41 21" src="https://user-images.githubusercontent.com/5982866/45014300-549ec980-b01e-11e8-94db-135ff2b1341b.png">
